# Modules: Datasets and Graphs

In [15]:
import tensorflow as tf
import tensorflow as tf
from tensorflow.keras.layers import Layer

from msp.datasets import make_data, load_sample_data, make_sparse_data
from msp.graphs import MSPGraph, MSPSparseGraph
from msp.models.encoders import GGCNEncoder

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [16]:
dataset = make_sparse_data(40, msp_size=(1,2), random_state=2021)

In [17]:
batch_size = 2
batch_dataset = dataset.batch(batch_size)
inputs = list(batch_dataset.take(1))[0]
inputs

MSPSparseGraph(adj_matrix=<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 1., 1.],
        [1., 0., 1.],
        [1., 1., 0.]],

       [[0., 1., 1.],
        [1., 0., 1.],
        [1., 1., 0.]]], dtype=float32)>, node_features=<tf.Tensor: shape=(2, 3, 5), dtype=float64, numpy=
array([[[0.60597828, 0.73336936, 0.13894716, 0.31267308, 1.        ],
        [0.12816238, 0.17899311, 0.75292543, 0.66216051, 1.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ]],

       [[0.82309863, 0.73222503, 0.06905627, 0.67212894, 1.        ],
        [0.82801437, 0.20446939, 0.61748895, 0.61770101, 1.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ]]])>, edge_features=<tf.Tensor: shape=(2, 3, 3, 3), dtype=float64, numpy=
array([[[[0.        , 0.        , 0.        ],
         [0.57430428, 0.37116084, 0.        ],
         [0.        , 0.        , 1.        ]],

        [[0.57430428, 0.37116084, 0.        ],
         [0.        ,

# Modules: Layers and Encoders

In [18]:
units = 6
layers = 2
ecoder_model = GGCNEncoder(units, layers)
embedded_inputs = ecoder_model(inputs)

In [19]:
inputs.node_features

<tf.Tensor: shape=(2, 3, 5), dtype=float64, numpy=
array([[[0.60597828, 0.73336936, 0.13894716, 0.31267308, 1.        ],
        [0.12816238, 0.17899311, 0.75292543, 0.66216051, 1.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ]],

       [[0.82309863, 0.73222503, 0.06905627, 0.67212894, 1.        ],
        [0.82801437, 0.20446939, 0.61748895, 0.61770101, 1.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ]]])>

In [20]:
embedded_inputs.node_features

<tf.Tensor: shape=(2, 3, 6), dtype=float32, numpy=
array([[[ 1.4795607 , -0.8077786 ,  0.7057835 , -0.99385923,
          1.5003251 ,  0.4199021 ],
        [ 1.9281734 , -0.5096461 ,  0.04622082, -0.54320633,
          1.6328988 , -0.3087515 ],
        [ 0.60056734,  0.74141127,  0.29764354,  0.28404447,
          0.24345967,  0.1397111 ]],

       [[ 1.811756  , -0.9319388 ,  0.52452755, -1.2279749 ,
          1.9755441 ,  0.52506274],
        [ 1.9187429 , -0.4659653 , -0.14419381, -0.62855065,
          1.7645391 ,  0.18608868],
        [ 0.6692883 ,  1.0349188 ,  0.31861427,  0.35426238,
          0.4175191 ,  0.13693845]]], dtype=float32)>

In [21]:
embedded_inputs.edge_features

<tf.Tensor: shape=(2, 3, 3, 6), dtype=float32, numpy=
array([[[[ 0.        ,  2.5219057 ,  0.        ,  0.4017915 ,
           0.2744972 ,  1.237106  ],
         [ 0.27844724,  1.381381  , -0.46594352,  0.7903234 ,
           0.04914367, -0.07825942],
         [ 0.20789123,  0.8720819 ,  0.5893204 , -0.25565568,
          -0.1333158 , -0.12449754]],

        [[ 0.78555965,  0.8397904 ,  0.6353665 ,  0.5672632 ,
           0.1590591 ,  0.4798256 ],
         [ 0.7132834 ,  0.45005906,  0.265978  ,  0.6750479 ,
           0.04947836,  0.09500669],
         [ 0.37467772, -0.5883572 ,  1.3862134 , -0.23055756,
          -0.1333158 ,  0.34080398]],

        [[ 0.58818257, -0.6484834 ,  0.37307614,  0.30639738,
           0.66805255,  1.0376089 ],
         [ 0.72384137, -0.6484834 ,  0.7095215 ,  0.5545557 ,
           0.5255828 ,  0.5689131 ],
         [ 0.        ,  0.08697002,  0.07256737,  0.        ,
           0.32654223,  0.8900547 ]]],


       [[[ 0.        ,  2.6647472 ,  0.        

In [22]:
inputs.edge_features

<tf.Tensor: shape=(2, 3, 3, 3), dtype=float64, numpy=
array([[[[0.        , 0.        , 0.        ],
         [0.57430428, 0.37116084, 0.        ],
         [0.        , 0.        , 1.        ]],

        [[0.57430428, 0.37116084, 0.        ],
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 1.        ]],

        [[0.        , 0.        , 1.        ],
         [0.        , 0.        , 1.        ],
         [0.        , 0.        , 0.        ]]],


       [[[0.        , 0.        , 0.        ],
         [0.70901567, 0.8906554 , 0.        ],
         [0.        , 0.        , 1.        ]],

        [[0.70901567, 0.8906554 , 0.        ],
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 1.        ]],

        [[0.        , 0.        , 1.        ],
         [0.        , 0.        , 1.        ],
         [0.        , 0.        , 0.        ]]]])>

In [20]:
MSPSparseGraph._fields

('adj_matrix', 'node_features', 'edge_features', 'alpha')

In [21]:
dataset = make_sparse_data(4, msp_size=(1,2), random_state=2021)

In [25]:
graph = list(dataset.take(1))[0]
graph

MSPSparseGraph(adj_matrix=<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]], dtype=float32)>, node_features=<tf.Tensor: shape=(3, 5), dtype=float64, numpy=
array([[0.27535218, 0.6795556 , 0.58162645, 0.97019879, 1.        ],
       [0.33048907, 0.96671416, 0.82589904, 0.30540018, 1.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])>, edge_features=<tf.Tensor: shape=(3, 3, 3), dtype=float64, numpy=
array([[[0.        , 0.        , 0.        ],
        [0.46459967, 0.12383996, 0.        ],
        [0.        , 0.        , 1.        ]],

       [[0.46459967, 0.12383996, 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 1.        ]],

       [[0.        , 0.        , 1.        ],
        [0.        , 0.        , 1.        ],
        [0.        , 0.        , 0.        ]]])>, alpha=<tf.Tensor: shape=(3, 1), dtype=float64, numpy=
array([[1.],
       [1.],
      

In [6]:
indices= tf.cast(tf.transpose(
    tf.concat([
        edge_index,
        tf.scatter_nd(
            tf.constant([[1],[0]]),
            edge_index,
            edge_index.shape
        )
    ], axis=-1)
), tf.int64)
indices

<tf.Tensor: shape=(6, 2), dtype=int64, numpy=
array([[0, 1],
       [0, 2],
       [1, 2],
       [1, 0],
       [2, 0],
       [2, 1]])>

In [7]:
adj_matrix = tf.sparse.SparseTensor(
    indices= indices,
    values = tf.ones([2*edge_index.shape[-1]]),
    dense_shape = [3,3]
)
adj_matrix

In [13]:
tf.sparse.to_dense(tf.sparse.reorder(adj_matrix))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]], dtype=float32)>

In [ ]:
reorder

In [31]:
tf.ones([edge_index.shape[-1]])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [38]:
E = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2], [2, 0]], values=[1, 2], dense_shape=[3, 4])
tf.sparse.to_dense()

ValueError: Dimensions 3 and 2 are not compatible

In [123]:
tf.ones((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [246]:
class GGCNLayer(Layer):

    # @validate_hyperparams
    def __init__(self, 
                 units,
                 *args, 
                 activation='relu', 
                 use_bias=True, 
                 normalization='batch',
                 aggregation='mean',
                 **kwargs):
        """ """
        super(GGCNLayer, self).__init__(*args, **kwargs)
        self.units = units
        self.activation = tf.keras.activations.get(activation)
        self.use_bias = use_bias
        self.normalization= normalization
        self.aggregation = aggregation

    def build(self, input_shape):
        """Create the state of the layer (weights)"""
        print('Build')
        node_features_shape = input_shape.node_features
        edge_featues_shape = input_shape.edge_features
        embedded_shape = tf.TensorShape((None, self.units))

        # _initial_projection_layer (think on it)

        with tf.name_scope('node'):
            with tf.name_scope('U'):
                self.U = tf.keras.layers.Dense(self.units, use_bias=self.use_bias)
                self.U.build(node_features_shape)

            with tf.name_scope('V'):
                self.V = tf.keras.layers.Dense(self.units, use_bias=self.use_bias)
                self.V.build(node_features_shape)

            with tf.name_scope('norm'):
                self.norm_h = {
                    "batch": tf.keras.layers.BatchNormalization(),
                    "layer": tf.keras.layers.LayerNormalization()
                }.get(self.normalization, None)
                if self.norm_h:
                    self.norm_h.build(embedded_shape)

        with tf.name_scope('edge'):
            with tf.name_scope('A'):
                self.A = tf.keras.layers.Dense(self.units, use_bias=self.use_bias)
                self.A.build(tf.TensorShape((None, node_features_shape[-1])))
            
            with tf.name_scope('B'):
                self.B = tf.keras.layers.Dense(self.units, use_bias=self.use_bias)
                self.B.build(node_features_shape)

            with tf.name_scope('C'):
                self.C = tf.keras.layers.Dense(self.units, use_bias=self.use_bias)
                self.C.build(edge_featues_shape)

            with tf.name_scope('norm'):
                self.norm_e = {
                    'batch': tf.keras.layers.BatchNormalization(),
                    'layer': tf.keras.layers.LayerNormalization(axis=-2)
                }.get(self.normalization, None)
                if self.norm_e:
                    self.norm_e.build(embedded_shape)
    
        super().build(input_shape)
 
    def call(self, inputs):
        """ """
        print('call')
        adj_matrix = inputs.adj_matrix
        h = inputs.node_features
        e = inputs.edge_features

        # Edges Featuers
        Ah = self.A(h)
        Bh = self.B(h)
        Ce = self.C(e)
        e = self._update_edges(e, [Ah, Bh, Ce])

        edge_gates = tf.sigmoid(e)

        # Nodes Features
        Uh = self.U(h)
        Vh = self.V(h)
        h = self._update_nodes(
            h,
            [Uh, self._aggregate(Vh, edge_gates, adj_matrix)]
        )

        outputs = MSPSparseGraph(adj_matrix, h, e, inputs.alpha)
        return inputs
        
    def _update_edges(self, e, transformations:list):
        """Update edges features"""
        Ah, Bh, Ce  = transformations
        e_new = tf.expand_dims(Ah, axis=1) + tf.expand_dims(Bh, axis=2) + Ce
        # Normalization
        batch_size, num_nodes, num_nodes, hidden_dim = e_new.shape
        if self.norm_e:
            e_new = tf.reshape(
                self.norm_e(
                    tf.reshape(e_new, [batch_size*num_nodes*num_nodes, hidden_dim])
                ), e_new.shape
            )
        # Activation
        e_new = self.activation(e_new)
        # Skip/residual Connection
        e_new = e + e_new
        return e_new

    def _update_nodes(self, h, transformations:list):
        """ """
        Uh, aggregated_messages = transformations
        h_new = tf.math.add_n([Uh, aggregated_messages])
        # Normalization
        batch_size, num_nodes, hidden_dim = h_new.shape
        if self.norm_h:
            h_new = tf.reshape(
                self.norm_h(
                    tf.reshape(h_new, [batch_size*num_nodes, hidden_dim])
                ), h_new.shape
            )
        # Activation
        h_new = self.activation(h_new)
        # Skip/residual Connection
        h_new = h + h_new
        return h_new

    def _aggregate(self, Vh, edge_gates, adj_matrix):
        """ """
        # Reshape as edge_gates
        Vh = tf.broadcast_to(
            tf.expand_dims(Vh, axis=1),
            edge_gates.shape
        )
        # Gating mechanism
        Vh = edge_gates * Vh
        
        # Enforce graph structure
        # mask = tf.broadcast_to(tf.expand_dims(adj_matrix,axis=-1), Vh.shape)
        # Vh[~mask] = 0

        # message aggregation
        if self.aggregation == 'mean':
            total_messages = tf.cast(
                tf.expand_dims(
                    tf.math.reduce_sum(adj_matrix, axis=-1),
                    axis=-1
                ),
                Vh.dtype
            )
            return tf.math.reduce_sum(Vh, axis=2) / total_messages
        
        elif self.aggregation == 'sum':
            return tf.math.reduce_sum(Vh, axis=2)


In [247]:
#

In [248]:

B, V, H = 1, 3, 2
h = tf.ones((B, V, H))


In [249]:
dataset = make_sparse_data(4, msp_size=(1,2), random_state=2020)
graphs = list(dataset.batch(2))
VVh = list(graphs)[0].edge_features
A = list(graphs)[0].adj_matrix
VVh.shape, A.shape

(TensorShape([2, 3, 3, 3]), TensorShape([2, 3, 3]))

In [252]:
# mask = tf.cast(tf.broadcast_to(
#     tf.expand_dims(A, axis=-1),
#     VVh.shape
# ), tf.bool)
# VVh[~mask] 
ggcn.variables

[<tf.Variable 'GGCN_Layer/node/U/kernel:0' shape=(5, 3) dtype=float32, numpy=
 array([[ 0.3418128 , -0.74846673,  0.4793586 ],
        [ 0.6570088 ,  0.8612539 ,  0.65150267],
        [-0.72393733, -0.22281748, -0.22313446],
        [ 0.79907125,  0.64225537, -0.03322494],
        [ 0.555322  ,  0.38448828,  0.36000997]], dtype=float32)>,
 <tf.Variable 'GGCN_Layer/node/U/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>,
 <tf.Variable 'GGCN_Layer/node/V/kernel:0' shape=(5, 3) dtype=float32, numpy=
 array([[-0.26467794,  0.7648507 ,  0.719668  ],
        [ 0.2005971 , -0.62737715, -0.5316253 ],
        [-0.05412966, -0.2538466 , -0.8192339 ],
        [ 0.02352881,  0.5495698 ,  0.2812906 ],
        [ 0.08741534,  0.04532963,  0.46388656]], dtype=float32)>,
 <tf.Variable 'GGCN_Layer/node/V/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>,
 <tf.Variable 'GGCN_Layer/node/norm/gamma:0' shape=(3,) dtype=float32, numpy=array([1., 1., 1.], d

In [251]:
units = graphs[0].edge_features.shape[-1]
ggcn = GGCNLayer(units=units, use_bias=True, name='GGCN_Layer')
output = ggcn(graphs[0])
output

Build
call


InvalidArgumentError: Incompatible shapes: [2,3,5] vs. [2,3,3] [Op:AddV2]

In [ ]:
tf.cast(
    tf.expand_dims(
        tf.math.reduce_sum(list(graphs)[0].adj_matrix, axis=-1),
        axis=-1
    ),
    Vh.dtype
)
    tf.expand_dims(
    tf.math.reduce_sum(list(graphs)[0].adj_matrix, axis=-1),
    axis=-1).dtype

In [54]:
tf.math.reduce_max(graphs[0].edge_features, axis=-2 )[0]

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[0.12417877, 0.31973648, 1.        ],
       [0.12417877, 0.31973648, 1.        ],
       [0.        , 0.        , 1.        ]])>

In [42]:
list(graphs)[0].adj_matrix

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 1., 1.],
        [1., 0., 1.],
        [1., 1., 0.]],

       [[0., 1., 1.],
        [1., 0., 1.],
        [1., 1., 0.]]], dtype=float32)>

In [51]:
# ggcn = GGCNLayer(units=units, use_bias=True, name='GGCN_Layer')
# output = ggcn(graphs[0])
# output

In [11]:
graphs = list(make_data(1, msp_size=(1,2), random_state=2021).take(1))[0]

num_edges = 3


A = tf.sparse.SparseTensor(
    indices= tf.cast(tf.transpose(graphs['edge_index']), tf.int64),
    values = tf.ones([num_edges]),
    dense_shape = [3,3]
)

tf.sparse.to_dense(A)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

In [34]:
tf.cast(tf.transpose(graphs['edge_index']), tf.int64)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[0, 1],
       [0, 2],
       [1, 2]])>

In [77]:
# ggcn.variables
tf.cast(tf.transpose(graphs['edge_index']), tf.int64)


<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[0, 1],
       [0, 2],
       [1, 2]])>

In [79]:
edge_index = tf.cast(tf.transpose(
    tf.concat([
        graphs['edge_index'],
        tf.scatter_nd(
            tf.constant([[1],[0]]),
            graphs['edge_index'],
            graphs['edge_index'].shape
        )
    ], axis=-1)
), tf.int32)
edge_index

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[0, 1],
       [0, 2],
       [1, 2],
       [1, 0],
       [2, 0],
       [2, 1]], dtype=int32)>

In [137]:
model = tf.keras.Sequential([
    GGCNLayer(units=units, use_bias=True, name='GGCN_Layer')
])
model.compile(optimizer='sgd', loss='mse')
model.fit(dataset)

ValueError: in user code:

    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:855 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:845 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:838 run_step  **
        outputs = model.train_step(data)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:795 train_step
        y_pred = self(x, training=True)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py:1030 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:375 call
        self._build_graph_network_for_inferred_shape(inputs.shape, inputs.dtype)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/training/tracking/base.py:522 _method_wrapper
        result = method(self, *args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:281 _build_graph_network_for_inferred_shape
        input_shape = tuple(input_shape)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/tensor_shape.py:868 __iter__
        raise ValueError("Cannot iterate over a shape with unknown rank.")

    ValueError: Cannot iterate over a shape with unknown rank.


In [86]:
model.weights

ValueError: Weights for model sequential have not yet been created. Weights are created when the Model is first called on inputs or `build()` is called with an `input_shape`.