# Modules: Datasets and Graphs

In [104]:
import tensorflow as tf
from msp.datasets import make_data, load_sample_data, make_sparse_data
from msp.graphs import MSPGraph

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [31]:
dataset = make_data(500, msp_rand_size=(2,30), random_state=2021)
tf.data.experimental.save(dataset, 'msp/datasets/data/sample_tf_rand_2021')

In [34]:
dataset = load_sample_data()

In [35]:
for sample in dataset:
    G = MSPGraph.from_dict(sample)
    file_name = "MSPGraph({}_{})".format(G.number_of_nodes(),G.number_of_edges())
    G.writeAs('msp/datasets/data/sample_graphml_rand_2021/{}.graphml'.format(file_name), 'graphml')

MSPGraph(45_759)
MSPGraph(42_690)
MSPGraph(33_150)
MSPGraph(20_172)
MSPGraph(35_364)
MSPGraph(37_413)
MSPGraph(10_44)
MSPGraph(14_46)
MSPGraph(28_287)
MSPGraph(12_54)
MSPGraph(42_483)
MSPGraph(26_295)
MSPGraph(47_675)
MSPGraph(22_140)
MSPGraph(20_37)
MSPGraph(21_39)
MSPGraph(37_495)
MSPGraph(48_875)
MSPGraph(34_483)
MSPGraph(25_222)
MSPGraph(24_242)
MSPGraph(22_191)
MSPGraph(18_132)
MSPGraph(35_516)
MSPGraph(24_156)
MSPGraph(40_429)
MSPGraph(34_523)
MSPGraph(32_435)
MSPGraph(42_770)
MSPGraph(24_234)
MSPGraph(42_455)
MSPGraph(22_176)
MSPGraph(34_183)
MSPGraph(37_456)
MSPGraph(23_198)
MSPGraph(31_114)
MSPGraph(31_59)
MSPGraph(34_308)
MSPGraph(43_552)
MSPGraph(47_756)
MSPGraph(24_230)
MSPGraph(41_649)
MSPGraph(27_180)
MSPGraph(21_193)
MSPGraph(29_378)
MSPGraph(18_62)
MSPGraph(23_133)
MSPGraph(38_493)
MSPGraph(40_627)
MSPGraph(30_393)
MSPGraph(29_367)
MSPGraph(40_609)
MSPGraph(31_406)
MSPGraph(37_621)
MSPGraph(19_80)
MSPGraph(31_416)
MSPGraph(42_741)
MSPGraph(46_864)
MSPGraph(41_752)
MSPGr

# Modules: Layers

In [5]:
from typing import NamedTuple

In [11]:
class Test(NamedTuple):
    node: tf.TensorSpec

In [75]:
from typing import NamedTuple

from tensorflow import Tensor

class GG:
    pass

class MSPSparseGraph(NamedTuple):
    """ """
    node_features: Tensor
    edge_features: Tensor
    # alpha: Tensor

    @property
    def num_node(self):
        return self.alpha.shape[0]
        #print('asdfjkas;df')

 

In [81]:
def _generator(n_samples):
    for i in range(n_samples):
        yield MSPSparseGraph(tf.ones((2,3)), tf.ones((5,2)))

In [87]:
# output_signature = {
# 'node_features': tf.TensorSpec(shape=None, dtype=tf.float64),
# 'edge_features': tf.TensorSpec(shape=None, dtype=tf.float64),
# 'edge_index': tf.TensorSpec(shape=None, dtype=tf.float64),
# 'alpha': tf.TensorSpec(shape=None, dtype=tf.float64)
# }

output_signature = MSPSparseGraph(tf.TensorSpec(shape=None, dtype=tf.float64), 
tf.TensorSpec(shape=None, dtype=tf.float64))
dataset = tf.data.Dataset.from_generator(_generator, args=(2,),
                                   output_signature=output_signature)
dataset.element_spec

MSPSparseGraph(node_features=TensorSpec(shape=<unknown>, dtype=tf.float64, name=None), edge_features=TensorSpec(shape=<unknown>, dtype=tf.float64, name=None))

In [88]:
list(dataset.take(1))[0]

MSPSparseGraph(node_features=<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>, edge_features=<tf.Tensor: shape=(5, 2), dtype=float64, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])>)

In [89]:
Graph(tf.ones((2,3)))._asdict()

OrderedDict([('node_features', <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
              array([[1., 1., 1.],
                     [1., 1., 1.]], dtype=float32)>)])

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Layer

In [2]:
# tf.compat.v1.disable_eager_execution()
# tf.compat.v1.enable_eager_execution()
tf.executing_eagerly()

True

In [3]:
class GGCNLayer(Layer):

    def __init__(self, 
                 units, 
                 *args, 
                 activation=None, 
                 use_bias=True, 
                 normalization='batch',
                 **kwargs):
        """ """
        super(GGCNLayer, self).__init__(*args, **kwargs)
        self.units = units
        self.activation = tf.keras.activations.get(activation)
        self.use_bias = use_bias
        self.normalization= normalization

    def build(self, input_shape):
        """Create the state of the layer (weights)"""
        print('Build')
        node_features_shape = input_shape  
        embedded_shape = tf.TensorShape((None, self.units))
        # _initial_projection_layer (think on it)

        with tf.name_scope('node'):
            with tf.name_scope('U'):
                self.U = tf.keras.layers.Dense(self.units, use_bias=self.use_bias)
                self.U.build(node_features_shape)

            with tf.name_scope('V'):
                self.V = tf.keras.layers.Dense(self.units, use_bias=self.use_bias)
                self.V.build(node_features_shape)

        with tf.name_scope('edge'):
            with tf.name_scope('A'):
                self.A = tf.keras.layers.Dense(self.units, use_bias=self.use_bias)
                self.A.build(tf.TensorShape((None, node_features_shape[-1])))
            
            with tf.name_scope('B'):
                self.B = tf.keras.layers.Dense(self.units, use_bias=self.use_bias)
                self.B.build(node_features_shape)

            with tf.name_scope('C'):
                self.C = tf.keras.layers.Dense(self.units, use_bias=self.use_bias)
                self.C.build(node_features_shape)

        with tf.name_scope('norm'):
            with tf.name_scope('node'):
                self.norm_h = {
                    "layer": tf.keras.layers.BatchNormalization(),
                    "batch": tf.keras.layers.LayerNormalization(),
                }.get(self.normalization)
                self.norm_h.build(embedded_shape)

            with tf.name_scope('edge'):
                self.norm_e = {
                    "layer": tf.keras.layers.BatchNormalization(),
                    "batch": tf.keras.layers.LayerNormalization(),
                }.get(self.normalization)
                self.norm_e.build(embedded_shape)
        
        super().build(input_shape)
 
    def call(self, inputs):
        """ """
        print('call')
        h = inputs

        Ah = self.A(h)
        Bh = self.B(h)





        return Ah


    def _convert_to_adjMatrix()


    # def _message_passing():

    #     def message_func():
    #         pass 

    #     def aggregate_func():
    #         pass 

    #     def update_func():
    #         pass

    #     # edge-wise
        
    #     update_func(
    #         aggregate_func(
    #             message_func(

    #             )
    #         )
    #     )

    

In [4]:
units = 4
B, V, H = 1, 3, 2
h = tf.ones((B, V, H))

In [5]:
ggcn = GGCNLayer(units=units, use_bias=True, name='GGCN_Layer')
output = ggcn(h)

Build
call


In [105]:
dataset = make_sparse_data(4, msp_size=(1,2), random_state=2021)

In [106]:
list(dataset.take(1))

InvalidArgumentError: TypeError: tile() missing 1 required positional argument: 'multiples'
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 645, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 961, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/content/drive/.shortcut-targets-by-id/1EYB6iJMFd35F7-IGCXdQBftrx1PpYRrJ/HSE_Thesis/msp/msp/datasets/_samples_generator.py", line 198, in _generator
    edge_features = sparse_repr(msp.to_dict())

  File "/content/drive/.shortcut-targets-by-id/1EYB6iJMFd35F7-IGCXdQBftrx1PpYRrJ/HSE_Thesis/msp/msp/datasets/_samples_generator.py", line 133, in sparse_repr
    tf.tile(graph['edge_features'], tf.constant([2,1], tf.int32))

TypeError: tile() missing 1 required positional argument: 'multiples'


	 [[{{node PyFunc}}]] [Op:IteratorGetNext]

In [47]:
tensor = tf.zeros((3,3,4))

updates = tf.ones((2,4))

indices = [[0, 2], [2,0]]

tf.tensor_scatter_nd_update(tensor, indices, updates).numpy()

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [52]:
def _convert_to_adjMatrix(graphs):
    """ """

    num_nodes = 3 #graphs['alpha'].shape[0]
    num_edge_features = 3 #edge_features.shape[-1]
    adjMatrix_shape = (num_nodes, num_nodes, num_edge_features)
    print(adjMatrix_shape)
    adjMatrix = tf.tensor_scatter_nd_update(
        tf.zeros(adjMatrix_shape),
        edge_index,
        edge_features
        #tf.transpose(tf.cast(graph['edge_index'], tf.int32)),
        #tf.cast(graph['edge_features'], tf.float32)
    )
    return adjMatrix

In [53]:
g = list(dataset.take(1))[0]
g

{'alpha': <tf.Tensor: shape=(3, 1), dtype=float64, numpy=
 array([[1.],
        [1.],
        [0.]])>,
 'edge_features': <tf.Tensor: shape=(3, 3), dtype=float64, numpy=
 array([[0.83727638, 0.07281021, 0.        ],
        [0.        , 0.        , 1.        ],
        [0.        , 0.        , 1.        ]])>,
 'edge_index': <tf.Tensor: shape=(2, 3), dtype=float64, numpy=
 array([[0., 0., 1.],
        [1., 2., 2.]])>,
 'node_features': <tf.Tensor: shape=(3, 3), dtype=float64, numpy=
 array([[0.13867598, 0.53071164, 0.31222526],
        [0.18790457, 0.94799318, 0.31926521],
        [0.        , 0.        , 0.        ]])>}

In [54]:
_convert_to_adjMatrix(list(dataset.take(1))[0])

(3, 3, 3)


<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0.        , 0.        , 0.        ],
        [0.19747274, 0.80559856, 0.        ],
        [0.        , 0.        , 1.        ]],

       [[0.19747274, 0.80559856, 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 1.        ]],

       [[0.        , 0.        , 1.        ],
        [0.        , 0.        , 1.        ],
        [0.        , 0.        , 0.        ]]], dtype=float32)>

In [49]:
_convert_to_adjMatrix(list(dataset.take(1))[0])

(1, 1, 3)


InvalidArgumentError: indices[0] = [0, 1] does not index into shape [1,1,3] [Op:TensorScatterUpdate]

In [109]:
dataset = make_data(4, msp_size=(1,2), random_state=2021)
list(dataset.take(1))[0]

{'alpha': <tf.Tensor: shape=(3, 1), dtype=float64, numpy=
 array([[1.],
        [1.],
        [0.]])>,
 'edge_features': <tf.Tensor: shape=(3, 3), dtype=float64, numpy=
 array([[0.57430429, 0.37116085, 0.        ],
        [0.        , 0.        , 1.        ],
        [0.        , 0.        , 1.        ]])>,
 'edge_index': <tf.Tensor: shape=(2, 3), dtype=float64, numpy=
 array([[0., 0., 1.],
        [1., 2., 2.]])>,
 'node_features': <tf.Tensor: shape=(3, 3), dtype=float64, numpy=
 array([[0.60597828, 0.73336936, 0.13894716],
        [0.12816238, 0.17899311, 0.75292543],
        [0.        , 0.        , 0.        ]])>}

In [110]:
graphs = list(dataset.take(1))[0]

edge_index = tf.cast(tf.transpose(
        tf.concat([
            graphs['edge_index'],
            tf.scatter_nd(
                tf.constant([[1],[0]]),
                graphs['edge_index'],
                graphs['edge_index'].shape
            )
        ], axis=-1)
    ), tf.int32)

edge_features = tf.cast(
        tf.tile(graphs['edge_features'], 
                tf.constant([2,1], tf.int32)), tf.float32)

num_nodes = graphs['alpha'].shape[0]
num_edge_features = edge_features.shape[-1]
adjMatrix_shape = (num_nodes, num_nodes, num_edge_features)  

tf.tensor_scatter_nd_update(
        tf.zeros(adjMatrix_shape),
         edge_index, # tf.transpose(tf.cast(graphs['edge_index'], tf.int32)),
        edge_features #tf.cast(graphs['edge_features'], tf.float32)
    
)



<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0.        , 0.        , 0.        ],
        [0.70901567, 0.8906554 , 0.        ],
        [0.        , 0.        , 1.        ]],

       [[0.70901567, 0.8906554 , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 1.        ]],

       [[0.        , 0.        , 1.        ],
        [0.        , 0.        , 1.        ],
        [0.        , 0.        , 0.        ]]], dtype=float32)>

In [61]:
edge_index

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[0, 1],
       [0, 2],
       [1, 2],
       [1, 0],
       [2, 0],
       [2, 1]], dtype=int32)>

In [ ]:
tf.cast(graphs['edge_features'], tf.float32)

In [34]:
tf.tensor_scatter_nd_update

<function tensorflow.python.ops.array_ops.tensor_scatter_nd_update>

In [35]:
_convert_to_adjMatrix(list(dataset.take(1))[0])
#tf.tile(list(dataset.take(1))[0]['edge_features'], tf.constant([2,1], tf.int32))

InvalidArgumentError: Value for attr 'Tindices' of double is not in the list of allowed values: int32, int64
	; NodeDef: {{node TensorScatterUpdate}}; Op<name=TensorScatterUpdate; signature=tensor:T, indices:Tindices, updates:T -> output:T; attr=T:type; attr=Tindices:type,allowed=[DT_INT32, DT_INT64]> [Op:TensorScatterUpdate]

In [11]:
indices = tf.constant([[1],[0]])
updates = tf.tile(edge_index, tf.constant([2,1], tf.int32))

shape = tf.constant([2, 4])
scatter1 = tf.scatter_nd(indices, updates, updates.shape)

NameError: name 'edge_index' is not defined

In [ ]:
node_features = Utils.get_node_feature_batch(inputs)
edge_features = 

In [293]:
edge_index = tf.transpose(list(dataset.take(1))[0]['edge_index'])
eee = tf.tile(edge_index, tf.constant([2,1], tf.int32))
eee

<tf.Tensor: shape=(6, 2), dtype=float64, numpy=
array([[0., 1.],
       [0., 2.],
       [1., 2.],
       [0., 1.],
       [0., 2.],
       [1., 2.]])>

In [314]:
indices = tf.constant([[1],[0]])
edge = list(dataset.take(1))[0]['edge_index']

tf.concat([
    edge,
    tf.scatter_nd(indices, edge, edge.shape)
], axis=-1)


<tf.Tensor: shape=(2, 6), dtype=float64, numpy=
array([[0., 0., 1., 1., 2., 2.],
       [1., 2., 2., 0., 0., 1.]])>

In [313]:
tf.scatter_nd(indices, edge, edge.shape)


<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 2., 2.],
       [0., 0., 1.]])>

In [298]:
tf.scatter_nd(tf.constant([[1],[0]]), tf.transpose(edge_index), edge_index.shape)

InvalidArgumentError: Dimensions [1,2) of input[shape=[3,2]] must match dimensions [1,2) of updates[shape=[2,3]] [Op:ScatterNd]

In [288]:
edge_index

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0., 1.],
       [0., 2.],
       [1., 2.]])>

In [280]:
edge_index

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0., 1.],
       [0., 2.],
       [1., 2.]])>

In [263]:
from collections import namedtuple
Data = namedtuple

In [256]:
graph['edge_features'], tf.cast(graph['edge_features'], tf.float32)

(<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
 array([[0.37378765, 0.58199336, 0.        ],
        [0.        , 0.        , 1.        ],
        [0.        , 0.        , 1.        ]])>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.37378764, 0.58199334, 0.        ],
        [0.        , 0.        , 1.        ],
        [0.        , 0.        , 1.        ]], dtype=float32)>)

In [270]:
graph = list(dataset.take(2))
graph[1]['node_features']
# tf.tensor_scatter_nd_update(
#     tf.zeros((3,3,3)),
#     tf.transpose(tf.cast(graph['edge_index'], tf.int32)),
#     tf.cast(graph['edge_features'], tf.float32)
# )

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[0.85199873, 0.949953  , 0.53910624],
       [0.17274769, 0.25472978, 0.83977326],
       [0.        , 0.        , 0.        ]])>

In [246]:
list(dataset.take(1))[0]['edge_features'].dtype
#list(dataset.take(1))[0]['edge_index']

tf.float64

In [274]:
list(dataset.batch(2))

[{'alpha': <tf.Tensor: shape=(2, 3, 1), dtype=float64, numpy=
  array([[[1.],
          [1.],
          [0.]],
  
         [[1.],
          [1.],
          [0.]]])>,
  'edge_features': <tf.Tensor: shape=(2, 3, 3), dtype=float64, numpy=
  array([[[0.35314496, 0.68720591, 0.        ],
          [0.        , 0.        , 1.        ],
          [0.        , 0.        , 1.        ]],
  
         [[0.23159023, 0.69815466, 0.        ],
          [0.        , 0.        , 1.        ],
          [0.        , 0.        , 1.        ]]])>,
  'edge_index': <tf.Tensor: shape=(2, 2, 3), dtype=float64, numpy=
  array([[[0., 0., 1.],
          [1., 2., 2.]],
  
         [[0., 0., 1.],
          [1., 2., 2.]]])>,
  'node_features': <tf.Tensor: shape=(2, 3, 3), dtype=float64, numpy=
  array([[[0.01272153, 0.39134668, 0.40923869],
          [0.03470439, 0.92181559, 0.81408223],
          [0.        , 0.        , 0.        ]],
  
         [[0.53559264, 0.15960381, 0.46659951],
          [0.32690014, 0.178752

In [241]:
_convert_to_adjMatrix(list(dataset.take(1))[0])

(3, 3, 3)


InvalidArgumentError: cannot compute TensorScatterUpdate as input #2(zero-based) was expected to be a float tensor but is a double tensor [Op:TensorScatterUpdate]

In [238]:
indices = tf.constant([[0], [2]])
updates = tf.constant([[[5, 5, 5, 5], [6, 6, 6, 6],
                    [7, 7, 7, 7], [8, 8, 8, 8]],
                    [[5, 5, 5, 5], [6, 6, 6, 6],
                    [7, 7, 7, 7], [8, 8, 8, 8]]])
shape = tf.constant([4, 4, 4])
scatter = tf.scatter_nd(indices, updates, shape)
print(scatter)

tf.Tensor(
[[[5 5 5 5]
  [6 6 6 6]
  [7 7 7 7]
  [8 8 8 8]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[5 5 5 5]
  [6 6 6 6]
  [7 7 7 7]
  [8 8 8 8]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]], shape=(4, 4, 4), dtype=int32)


In [213]:
indices = tf.constant([[0]])
updates = tf.constant([[[1,2,3]]])
shape = (4,4,3)
scatter = tf.scatter_nd(indices, updates, shape)
print(scatter)

InvalidArgumentError: Dimensions [1,3) of input[shape=[4,4,3]] must match dimensions [1,3) of updates[shape=[1,1,3]] [Op:ScatterNd]

In [180]:
from scipy import sparse
adj = [[1,2]]
data = [2,3,4]
sparse.coo_matrix(([[1,3,2],[3,4,3]], ([1,2], [2,1])), (10, 10,3))


ValueError: too many values to unpack (expected 2)

In [84]:
vh = torch.ones((1,2,2,3))
g = torch.ones((1,2,2))
g.unsqueeze(-1).expand_as(vh)

tensor([[[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]]])

In [92]:
tf.ones((2,3))[tf.constant([[1,0,1],[0,1,1]])]

InvalidArgumentError: Expected begin, end, and strides to be 1D equal size tensors, but got shapes [1,2,3], [1,2,3], and [1] instead. [Op:StridedSlice] name: strided_slice/

In [133]:
import numpy as np
G = 2*torch.ones((2,3))
print(G)
mask = torch.tensor([[1,0,1],[0,1,0]], dtype=torch.bool)
print(mask)
G[~mask] = 0
G

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[ True, False,  True],
        [False,  True, False]])


tensor([[2., 0., 2.],
        [0., 2., 0.]])

In [187]:
tf.ones((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [191]:
tensor = tf.zeros((3,3,4))

updates = tf.ones((2,4))

indices = [[0, 2], [2,0]]

tf.tensor_scatter_nd_update(tensor, indices, updates).numpy()

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [145]:
torch.sum(torch.ones((2,3,4)),1).shape

torch.Size([2, 4])

In [140]:
graph = torch.tensor([[1,0,1],[0,1,0]], dtype=torch.long).unsqueeze(0)
torch.sum(graph, dim=2).unsqueeze(-1)

tensor([[[2],
         [1]]])

In [ ]:
tf.ones(2,3,)

In [124]:
torch.tensor([[1,0,0],[0,1,0]], dtype=torch.bool)

tensor([[ True, False, False],
        [False,  True, False]])

In [112]:
torch.Tensor(np.array([[1,0,0],[0,1,0]]), dtype='long')

TypeError: new() received an invalid combination of arguments - got (numpy.ndarray, dtype=str), but expected one of:
 * (*, torch.device device)
      didn't match because some of the keywords were incorrect: dtype
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
 * (object data, *, torch.device device)


In [130]:
Ah = tf.ones((5,3,4))

s = list(Ah.shape)
s[-1:-1] = [100]
s
tf.TensorShape([23,4])


TensorShape([23, 4])

In [ ]:
from collections import defaultdict 


In [115]:
tf.ones((2,3)) #* tf.ones((2))

tf.broadcast_to(
    tf.expand_dims(tf.ones((2,2,3)), 0),
     tf.TensorShape((5, 2, 2, 3))
)




<tf.Tensor: shape=(5, 2, 2, 3), dtype=float32, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]], dtype=float32)>

In [62]:
import torch


torch.ones((1,2,3)).unsqueeze(1).expand(-1,2,-1,-1)

tensor([[[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]]])

In [6]:
#output
tf.expand_dims(output,1)

<tf.Tensor: shape=(1, 1, 3, 4), dtype=float32, numpy=
array([[[[-0.6347897, -1.5240858, -0.2905345, -1.2611516],
         [-0.6347897, -1.5240858, -0.2905345, -1.2611516],
         [-0.6347897, -1.5240858, -0.2905345, -1.2611516]]]],
      dtype=float32)>

In [7]:
ggcn.variables

[<tf.Variable 'GGCN_Layer/node/U/kernel:0' shape=(2, 4) dtype=float32, numpy=
 array([[-0.7908015 , -0.31756973,  0.9770453 , -0.86365485],
        [ 0.57385945,  0.3395264 ,  0.39369655, -0.9945414 ]],
       dtype=float32)>,
 <tf.Variable 'GGCN_Layer/node/U/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'GGCN_Layer/node/V/kernel:0' shape=(2, 4) dtype=float32, numpy=
 array([[-0.63925743,  0.42692327,  0.81665325, -0.58390784],
        [ 0.33103204,  0.02955723, -0.995662  , -0.36471272]],
       dtype=float32)>,
 <tf.Variable 'GGCN_Layer/node/V/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'GGCN_Layer/edge/A/kernel:0' shape=(2, 4) dtype=float32, numpy=
 array([[-0.2605679 , -0.85975766,  0.5714941 , -0.54330873],
        [-0.3742218 , -0.6643281 , -0.8620286 , -0.7178428 ]],
       dtype=float32)>,
 <tf.Variable 'GGCN_Layer/edge/A/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0.,

In [11]:
        # self.w = self.add_weight(shape=(input_shape[-1], self.units),
        #                          initializer='random_normal',
        #                          trainable=True)
        # self.b = self.add_weight(shape=(self.units,),
        #                          initializer='random_normal',
        #                          trainable=True)

In [ ]:
import networkx as nx
import numpy as np
import tensorflow as tf

import itertools
import functools

from tensorflow.data import Dataset
from tensorflow.python.data.ops.dataset_ops import FlatMapDataset

In [ ]:
%load_ext autoreload
%autoreload 2

from msp.datasets import make_data, load_sample_data
from msp.graphs import MSPGraph


In [ ]:
dataset = make_data(1, msp_rand_size=(10,80))
G = MSPGraph.from_dict(list(dataset.take(1))[0])

In [ ]:
degrees = [val for (node, val) in G.degree() if val==0]

import numpy as np
np.random.randint(*(5,80), size=2).sum()

In [ ]:
G.alpha

In [ ]:
alpha = G.alpha


alpha_2 = ','.join(map(str, alpha.numpy().flatten()))

alpha_3 = tf.constant(np.array(alpha_2.split(','), dtype='float').reshape(alpha.shape))

In [ ]:
G.number_of_nodes()

In [ ]:
G.writeAs('file.graphml', 'graphml')

In [ ]:
G.number_of_nodes(), G.number_of_edges()

In [ ]:
#G.edges

In [ ]:
GG = nx.read_graphml('file.graphml')

In [ ]:
GG.graph['alpha']

In [ ]:
tf.data.experimental.save(dataset, 'msp/datasets/data/sample_msp_tf_1')

In [ ]:
dataset = load_sample_data()

In [ ]:
from msp.graphs import MSPGraph
G = MSPGraph.from_dict(list(dataset.take(1))[0])

from networkx.drawing.nx_pydot import write_dot
# pos = nx.nx_agraph.graphviz_layout(G)
# nx.draw(G, pos=pos)
write_dot(G, 'file.dot')

In [ ]:
G.graph['alpha'] = 'Graph____Attributes'

In [ ]:
nx.write_graphml_lxml(G, "file.graphml")

In [ ]:
d = load_sample_data()

In [ ]:
d

In [ ]:
dataset

In [ ]:
tf.data.experimental.save(dataset, 'data/sample_tf')

In [ ]:
new_dataset = tf.data.experimental.load('data/sample_tf', compression='GZIP')

In [ ]:
list(dataset.take(2))

In [ ]:
list(new_dataset.take(5))

In [ ]:
os.path.dirname(__file__)

In [ ]:
from os.path import dirname
dirname(__file__)

In [ ]:
import os
os.path.dirname(__file__) + os.path.basename(__file__)

In [ ]:
for i,j in zip(new_dataset,dataset):
    print(i)
    print(j)
    print('=====')

In [ ]:
G = MSPGraph.from_dict(list(dataset.take(1))[0])
G.number_of_nodes()

In [ ]:
tf.data.Dataset(dataset)

In [ ]:
tf.data.Dataset.range(10)

In [ ]:
tf.data.experimental.save(dataset, 'data/')

In [ ]:
d = tf.data.experimental.load('data/', element_spec=None, compression=None, reader_func=None)

In [ ]:
import tempfile
path = 'data/' #os.path.join(tempfile.gettempdir(), "saved_data")
# Save a dataset
dataset = tf.data.Dataset.range(2)
tf.data.experimental.save(dataset, path)
new_dataset = tf.data.experimental.load(path)
for elem in new_dataset:
  print(elem)



In [ ]:
new_dataset

In [ ]:
import inspect

print(inspect.getsource(tf.data.Dataset.from_generator))

In [ ]:
dataset = make_data(1, msp_size=(20,80))
G = MSPGraph.from_dict(list(dataset.take(1))[0])
G.number_of_nodes()

In [ ]:
dir(FlatMapDataset)

In [ ]:
G.to_gexf()

In [ ]:
node_features = G.node_features
node_features

In [ ]:
nodes = range(node_features.shape[0])

node_feat_name = None    
if node_feat_name is None:
    node_feat_name = ['nfeature_'+str(i+1) for i in nodes]

# dict(zip(node_feat_name,vec))
node_for_adding = zip(
    nodes,
    map(lambda vec: dict(zip(node_feat_name,vec.numpy())), node_features)
)
list(node_for_adding)

In [ ]:
MSPGraph()

In [ ]:
from msp.datasets import make_data, MSPGraph
_generator = make_data(1, msp_size=(4,10))
node_features, edge_features, alpha, edge_index, G = _generator(1)

In [ ]:
nx.draw_networkx(G)

In [ ]:
G.edge_index

In [ ]:
G2 = G.to_dict()

In [ ]:
G2

In [ ]:
MSPGraph.from_dict(G2).to_dict()

In [ ]:
node_features

In [ ]:
G.node_features

In [ ]:
edge_features

In [ ]:
G.edge_features

In [ ]:
edge_index

In [ ]:
G.edge_index

In [ ]:
G.alpha

In [ ]:
alpha

In [ ]:
from msp.datasets import MSPGraph
G2 = MSPGraph.from_dict(G.to_dict())
G2.to_dict()

In [ ]:
for i in G2.nodes(data=True)._nodes.values():
    print(tf.constant([*i.values()]))
    break

In [ ]:
G.to_dict()

In [ ]:
x = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]])
np.array(np.array(x)).T

In [ ]:
_generator = make_data(1, msp_size=(2,5))
node_features, alpha, edge_index, msp = _generator(1)

In [ ]:
node_features

In [ ]:
alpha

In [ ]:
edge_index

In [ ]:
from msp.utils import _is_connected

In [ ]:
np.array(list(
    filter(
        functools.partial(_is_connected, node_features, alpha),
        itertools.combinations(range(7), 2)
    )
)).T

In [ ]:
g = list(itertools.combinations(range(7), 2))
np.array(g).reshape(2,-1)

In [ ]:
G = msp

In [ ]:
G.number_of_nodes()
G.number_of_edges()
list(G.nodes)
list(G.edges)
list(G.adj[1])
list(G.neighbors(1))
G.degree[1]  
G.edges([2, 4])
G.degree([2, 3])
G[3]
nx.draw(G, with_labels=True, font_weight='bold')

In [ ]:
G.edges

In [ ]:
edge_index

In [ ]:
G.nodes(data=True)[0]

In [ ]:
G

In [ ]:
_generator(1)

In [ ]:
A = np.array([[1,2],[4,5]])
list(map(lambda x,y: tuple(x)+(y,),  A, [{'af':'sdf'},{'af':'sdf'}]))

In [ ]:
map(
---> 51             lambda e_indx,attr: e_indx+(attr,),
     52             edge_index.T,
     53             map(lambda vec: dict(zip(edge_feat_name,vec)), edge_features)

In [ ]:
tf.Tensor

In [ ]:
B = tf.convert_to_tensor(A)
if not isinstance(B, tf.Tensor):
    print('asdfa')

In [ ]:
tf.enable_eager_execution?
A = np.random.rand(3,4)
r = tf.convert_to_tensor(A)
type(r)

In [ ]:
import numpy as np

def my_func(arg):
  arg = tf.convert_to_tensor(arg, dtype=tf.float32)
  return arg

# The following calls are equivalent.

value_1 = my_func(tf.constant([[1.0, 2.0], [3.0, 4.0]]))
print(value_1, type(value_1))



value_2 = my_func([[1.0, 2.0], [3.0, 4.0]])
print(value_2)



value_3 =  tf.convert_to_tensor(A)
print(value_3)




In [ ]:
edge_features = sup(2, msp_size=(2,5))
edge_features

In [ ]:
edge_features == 1

In [ ]:
edge_type

In [ ]:
edge_index

In [ ]:
node_features

In [ ]:
sup(2, node_feat_size=5, edge_feat_size=3, msp_size=(3,12))

In [ ]:
sup(2)

In [ ]:
def f(c):
    print('dd', c)
    return c

a,b,c = 0,1,1
all((
    a and
    b and
    f(c) == 0
,)

)



In [ ]:
if not any([0,0]) or 0:
    print('343')

In [ ]:
iter(1,2,f(3))




In [ ]:
from msp.datasets import make_data

In [ ]:
any([2,0])

In [ ]:
d = make_data(2)
d

In [ ]:
list(d.take(1))

In [ ]:
from msp import datasets

In [ ]:
from msp.datasets import make_data

In [ ]:
from msp.datasets import make_data

In [ ]:
for i in make_data(2):
    print(i)

In [ ]:
 make_data(2)

In [ ]:
def fun(a, b):
    print(a,b)
    return a, b

g = {'a':34, 'b':43}
fun(**g)

In [ ]:
from sklearn.utils import check_random_state
seed = check_random_state(None)

a = (1, 1000)
n_machines, n_jobs = seed.randint(*a, size=2)
n_machines, n_jobs, seed.randint(*a, size=2)

In [ ]:
np.random.randint?

In [ ]:
{'fadsf':3}()

In [ ]:
edge_index = [(20,4)]
at = [dict(a=90)]

list(map(lambda x,y: x+(y,), edge_index, at))


In [ ]:
          map(lambda edge: node_features[edge[0]][-1], edge_index)),
          map(lambda edge: node_features[edge[1]][-1], edge_index))

In [ ]:



list(zip(*edge_index,*edge_index[2], [dict(a=90)]))

In [ ]:
F = np.random.rand(3,2)
nodes = [20, 4, 5]


l1 = zip(nodes, map(lambda vec: dict(zip(s,vec)), F))
G = nx.Graph()
G.add_nodes_from(l1)
G.add_edges_from([(20,5,dict(a=893,b=90))])
G.add_edges_from([(5,4,dict(a=893,b=90))])

G.graph = {'fadf':32}

nx.draw(G, with_labels=True)

g = np.array(list(map(
    lambda _dict: np.array([*_dict.values()]),
    G.nodes(data=True)._nodes.values()
)))
g

# G.edges, G.adj, list(G.adjacency())

# G.edges(data=True)._adjdict.values()

import operator

np.array(list(map(
    lambda e: np.array([*e[-1].values()]),
    list(G.edges(data=True))
)))

In [ ]:
l2 = [(1, dict(size=11)), (2, {"color": "blue"})]
l2

In [ ]:
F = np.random.rand(3,2)
nodes = [20, 4, 5]
F = [11, 'blue']
list(zip(nodes, map(lambda x: dict(da=x),F)))

In [ ]:
G = nx.Graph(name="my graph")
G.add_nodes_from(l2)

In [ ]:
nx.draw(G, with_labels=True)
G.nodes(data=True)
G.graph

In [ ]:
import itertools 

In [ ]:
it.combinations([1,2,4], [1,2,4])

In [ ]:
import operator
a = [(0, 1), (0, 1), (0, 0), (1,0)]
first, snd = zip(*a)
r = np.logical_xor(first, list(map(lambda x: x[1], a))).reshape((-1,1))

np.random.rand(4,2) * np.invert(r).astype('int')
#list(map(operator.itemgetter(0),a))


In [ ]:
alpha = np.random.randn(3,4)
alpha

In [ ]:
np.

In [ ]:
np.dot(alpha[0], alpha[1])

In [ ]:
np.sum(alpha[0]*alpha[1])

In [ ]:
not np.any([1,1,1])

In [ ]:
def a() -> int:
    return 0